version: "3.7"
services:
  nginx:
    image: nginx:1.17.0-alpine
    ports:
      - "80:80"
    depends_on:
      - ruby
  pgdb:
    # dc exec pgdb psql -Upostgres
    # dc exec pgdb pg_dump -s -x -O -f /usr/src/app/db/structure.sql worktime_dev
    image: postgres:11.4-alpine
    environment:
      PG_PASSWORD: password
    volumes:
      - db:/var/lib/postgresql/data
  pgdb-test:
    image: postgres:11.4-alpine
    environment:
      PG_PASSWORD: password
    tmpfs:
      - /var/lib/postgresql/data
  ruby: &app_base
    build:
      context: ./worktime-rails
      dockerfile: docker/Dockerfile
    environment:
      RAILS_ENV: development
      DATABASE_NAME: worktime_dev
      DATABASE_HOST: pgdb
      DATABASE_PORT: 5432
      RAILS_MAX_THREADS: 5
      DATABASE_USERNAME: postgres
      BUNDLE_APP_CONFIG: /usr/src/app/.bundle
      BUNDLE_PATH: /usr/src/app/vendor/bundle
    ports:
      - "3000:3000"
    volumes:
      - ./worktime-rails/app:/usr/src/app/app
      - ./worktime-rails/bin:/usr/src/app/bin
      - ./worktime-rails/config:/usr/src/app/config
      - ./worktime-rails/db:/usr/src/app/db
      - ./worktime-rails/lib:/usr/src/app/lib
      - ./worktime-rails/public:/usr/src/app/public
      - ./worktime-rails/storage:/usr/src/app/storage
      - ./worktime-rails/vendor:/usr/src/app/vendor
      - ./worktime-rails/.bundle:/usr/src/app/.bundle
      - ./worktime-rails/.rubocop.yml:/usr/src/app/.rubocop.yml
      - ./worktime-rails/config.ru:/usr/src/app/config.ru
      - ./worktime-rails/Gemfile:/usr/src/app/Gemfile
      - ./worktime-rails/Gemfile.lock:/usr/src/app/Gemfile.lock
      - ./worktime-rails/Rakefile:/usr/src/app/Rakefile
    depends_on:
      - pgdb
    command: /bin/sh -c "bundle exec rails server -p 3000 -b 0.0.0.0"
    tty: true
    stdin_open: true
  spring: # container for rake tasks
    # dc exec spring bin/rails -T
    # dc exec spring bin/rails db:create
    # dc exec spring bin/rails db:migrate
    <<: *app_base
    command: ["bundle", "exec", "spring", "server"]
    ports: []
    tty: false
    stdin_open: false
  rspec:
    # dc exec rspec bin/rspec
    # dc exec rspec bundle exec rspec
    # dc exec rspec bundle exec guard
    <<: *app_base
    environment:
      RAILS_ENV: test
      DATABASE_NAME: worktime_test
      DATABASE_HOST: pgdb-test
      DATABASE_PORT: 5432
      RAILS_MAX_THREADS: 5
      DATABASE_USERNAME: postgres
      BUNDLE_APP_CONFIG: /usr/src/app/.bundle
      BUNDLE_PATH: /usr/src/app/vendor/bundle
    command: ["bundle", "exec", "spring", "server"]
    ports: []
    depends_on:
      - pgdb-test
  fluentd:
    image: fluent/fluentd:v1.6-1
volumes:
  db:
