version: "3"
services:
  web:
    image: nginx:1.15.7-alpine
    ports:
      - "80:80"
  postgresql:
    image: postgres:11.1-alpine
    environment:
      PG_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql
volumes:
  db:
