version: "3.7"
services:
  web:
    image: nginx:1.17.0-alpine
    ports:
      - "80:80"
  postgresql:
    image: postgres:11.4-alpine
    environment:
      PG_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql
volumes:
  db:
